//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dashboard_HospitalGuide_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artical
    {
        public int Artical_ID { get; set; }
        public string Artical_title { get; set; }
        public string Artical_Subtitle { get; set; }
        public Nullable<System.DateTime> Artical_Date { get; set; }
        public string Artical_Image { get; set; }
        public string Artical_Content { get; set; }
        public Nullable<int> Admin_ID { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
