//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dashboard_HospitalGuide_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hospital_Services_GiudDBEntities : DbContext
    {
        public Hospital_Services_GiudDBEntities()
            : base("name=Hospital_Services_GiudDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Care_Units> Care_Units { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Artical> Articals { get; set; }
        public virtual DbSet<Newss> Newsses { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<Blood> Bloods { get; set; }
        public virtual DbSet<BloodNeed> BloodNeeds { get; set; }
    }
}
