//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dashboard_HospitalGuide_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.patients = new HashSet<patient>();
        }
    
        public int dept_ID { get; set; }
        public string dept_Name { get; set; }
        public int dept_NumberOfemptybed { get; set; }
        public int dept_NumberOfBed { get; set; }
        public string dept_Info { get; set; }
        public string dept_Descripation { get; set; }
        public int dept_NumberOfEmp { get; set; }
        public int Admin_ID { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient> patients { get; set; }
    }
}
