//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dashboard_HospitalGuide_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newss
    {
        public int News_ID { get; set; }
        public string News_Content { get; set; }
        public string News_Image { get; set; }
        public System.DateTime News_Date { get; set; }
        public Nullable<int> Admin_ID { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
