//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dashboard_HospitalGuide_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int Patient_ID { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<System.DateTime> Patient_DateOfBirth { get; set; }
        public string Patient_PhoneNumber { get; set; }
        public string Patient_Gender { get; set; }
        public string Patient_NationalID { get; set; }
        public string Patient_Address { get; set; }
        public Nullable<int> Admin_ID { get; set; }
        public Nullable<int> dept_ID { get; set; }
        public Nullable<int> Care_ID { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Care_Units Care_Units { get; set; }
        public virtual Department Department { get; set; }
    }
}
